# _config.yml

# required, replace with your own information -----
title: Mevlüt Hançerkıran
author: Mevlüt Hançerkıran
description: > 
  Mevlüt Hançerkıran's Personal Website
baseurl: "https://mevluthancerkiran.github.io/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

